### ISSUE TITLE
error report : fastq reader

### ISSUE THREAD

**Issue by JYLeeBioinfo** [rvolden/10xR2C2#2]
Due to this part of the code, racon fails.

```
#MergeUMIs.py
158 :      name, seed = split_name[0], 0
```

Since the subreads matching with a consensus share the same rootnames, setting seed=0 causes a racon error as following due to the same subread names between different subreads

```
[hrs@node12 PM-PS-0001-T_R2C2_q7_pass_merged.fastq_step02_c3poa_post]$ cat ../racon_messages.txt
[racon::Polisher::initialize] loaded target sequences 0.000187 s
[racon::Polisher::initialize] loaded sequences 0.000122 s
[racon::Overlap::transmute] error: unequal lengths in sequence and overlap file for sequence 3d5c86cb-ffb5-4813-958c-356360cfc519_0!
```

**Comment by rvolden** [comment]
Most recent push should resolve this. It will keep the original subread header for when it writes the temporary fastq for racon (original header is unique).

**Comment by JYLeeBioinfo** [comment]
Thank you for your fast response!
I'll try the new one.
